#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CSI 500, Python Assignment #3
Jericho McLeod
jmcleod3@gmu.edu


Problem 1: File Input and Output
"""

import csv

dat = []
with open('cryptocurrency.csv',encoding='utf-8-sig') as csvfile:
    csvreader = csv.reader(csvfile,delimiter=',')
    for row in csvreader:
        dat.append(row)


                                            # Calculate total market value for each crypto currency
for i in dat:                               #iterate through rows
    for j in i:                             #iterate through columns
        try:                                #if field is a number, convert to number, if not, pass
            j=float(j)
        except: pass
    try:                                    #if row is not text, 4th column = 2nd col * 3rd col value
        i[3] = round(float(i[2])*float(i[1]), 2)
    except:
        pass

                                            # Calculate market values
count=0                                     # Row counter variable
for i in dat[-1]:                           # Iterate through bottom row
    if i == "":                             # If the cell is empty, calculate it
        temp=0                              # Summation variable
        for x in dat:                       # Iterate through prior rows
            if count>0:                     # But skip the first one
                try:                        # Adding up the values in rows after the first row with the current column position
                    temp+=float(x[count])
                except: pass                # Except for the first column
        dat[-1][count]=round(temp,2)        # Writing the values to list of lists dataframe
    count+=1                                # Update row counter variable


for i in dat:                               #Check output
    print(i)

with open('cryptocurrency_calc.csv','w',encoding='utf-8-sig') as csvfile:
    csvwriter = csv.writer(csvfile, delimiter=',')
    for i in dat:
        csvwriter.writerow(i)
        
        
#%%
        
''' Problem 2: Classes and Objects

Output:
Radius: 2, Center (x,y) coordinates: (3, 3)
Radius: 2, Center (x,y) coordinates: (2, 2)
12.566

'''
        
class Point:                                # Point class 
    def __init__(self,x=0,y=0):             # Default values
        self.x=x
        self.y=y
    def __str__(self):                      # String return for point class
        return('(%0s, %0s)' %(self.x,self.y))

class Circle:                               # Circle Class
    def __init__(self,radius=0,center=(0,0)):
        self.radius = radius
        Point.__init__(self,center)
        self.center = center
    def print_circle(self):                 # Print definition rather than string return
        print('Radius: %0s, Center (x,y) coordinates: %0s' \
              %(self.radius,self.center))
    def move_center(self,new_point):        # Redefine center point to show mutability
        Point.__init__(self,new_point)
        self.center = new_point
    def area(self):                         # calculate area
        import math
        self.area = math.pi * self.radius**2
        return(self.area)

circle = Circle(2,(3,3))                    #instantiate circle
circle.print_circle()                       #call print function
circle.move_center((2,2))                   #call move function
circle.print_circle()                       #call print function a second time to show movement
area = round(circle.area(),3)               #call area function to variable definition
print(area)                                 #print area variable





























